services:
  app:
    image: uidgen
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - etcd
    environment:
      - UIDGEN_DATACENTER_ID=0
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
  nginx:
    image: nginx:1.25.5-alpine3.19
    container_name: nginx-lb
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
  etcd:
    image: bitnami/etcd:3.5.13
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
